### ISSUE TITLE
Confusing point estimates for association parameters in current values + current slopes model

### ISSUE THREAD

**Issue by amirabadiza921** [drizopoulos/JMbayes2#54]
Hi Dr. Rizopoulos,
When I run the current values+ current slopes, I get point estimates of assoct = 4.27 (SE = 1.03) and assoct.s = 28.10 (SE=4.86).

model.cox<-coxph(Surv(surv_time,incidenceCKD)~sex15_1+age+FHD+ waist+fbs+bs2HR+BMI,data=data.cox,x=T,model=TRUE)
fit.lm1<-lme(FT4~time,random= ~time | code,data=dataLong)
ffm<-list("FT4" = ~ value(FT4) + slope(FT4))
fit.JM<-jm(model.cox,fit.lm1,functional_forms = ffm,time_var="time")
summary(fit.JM)
Thanks

**Comment by drizopoulos** [comment]
It is not clear what exactly the issue is. If the model has converged, the magnitude of the coefficients needs to be interpreted, accounting for the scale of the longitudinal outcome. For example, is the random slopes are very small in magnitude per subject, it is logical to get a large coefficient for the slope.
