### ISSUE TITLE
Coefficient interpretation when using survreg as the survival submodel

### ISSUE THREAD

**Issue by jim-rafferty** [drizopoulos/JMbayes2#98]
Hi Dimitris,

Apologies if this is an obvious question. I'm enjoying using this library but am wondering how to interpret the results when I use a parametric survival model (fit using `survreg` from `survival`) as the survival submodel.

Here is my code:
```
fm1 = lme(fixed=log(serBilir) ~ 1, random = ~year | id, data=pbc2) 
fCox1 = coxph(Surv(years, status2) ~ drug * age, data=pbc2.id)
joint_model_cox_fit_1 =  jm(fCox1, fm1, time_var = "year", n_chains=1L, n_iter=11000L, n_burnin=1000L)
```
If I inspect the coefficients from the Cox model and the joint model, the values differ a bit as you would expect, but the signs of the coefficients are the same so I assume the interpretation is the same (ie they are hazard ratios).

Using a parametric model instead of a Cox model
```
fm1 = lme(fixed=log(serBilir) ~ 1, random = ~year | id, data=pbc2)
fSurv1 = survreg(Surv(years, status2) ~ drug * age, data=pbc2.id, dist="weibull")
joint_model_fit_1 =  jm(fSurv1, fm1, time_var = "year", n_chains=1L, n_iter=11000L, n_burnin=1000L) 
```
inspecting the coefficients of `fSurv1` and the joint model separately, they change sign. The coefficients from the parametric model are AFT coefficients, so they have a different interpretation to the hazard ratios from a proportional hazards model. How do I interpret the coefficients from a joint model with a parametric survival submodel? Is `JMbayes2` converting to hazard ratios under the hood? This behaviours also there when I specify a log-logistic parametric model, where it shouldn't be possible to extract hazard ratios from the coefficients, so I am rather confused.

Thank you!

**Comment by drizopoulos** [comment]
JMbayes2 only fits proportional hazards models. The coxph or survreg objects are only used to extract the data to fit the joint model.

——
Professor of Biostatistics
Erasmus Medical Center Rotterdam
The Netherlands
________________________________
Από: jim-rafferty ***@***.***>
Στάλθηκε: Thursday, August 1, 2024 1:55:14 PM
Προς: drizopoulos/JMbayes2 ***@***.***>
Κοιν.: Subscribed ***@***.***>
Θέμα: [drizopoulos/JMbayes2] Coefficient interpretation when using survreg as the survival submodel (Issue #98)



Waarschuwing: Deze e-mail is afkomstig van buiten de organisatie. Klik niet op links en open geen bijlagen, tenzij u de afzender herkent en weet dat de inhoud veilig is.
Caution: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.



Hi Dimitris,

Apologies if this is an obvious question. I'm enjoying using this library but am wondering how to interpret the results when I use a parametric survival model (fit using survreg from survival) as the survival submodel.

Here is my code:

fm1 = lme(fixed=log(serBilir) ~ 1, random = ~year | id, data=pbc2)
fCox1 = coxph(Surv(years, status2) ~ drug * age, data=pbc2.id)
joint_model_cox_fit_1 =  jm(fCox1, fm1, time_var = "year", n_chains=1L, n_iter=11000L, n_burnin=1000L)


If I inspect the coefficients from the Cox model and the joint model, the values differ a bit as you would expect, but the signs of the coefficients are the same so I assume the interpretation is the same (ie they are hazard ratios).

Using a parametric model instead of a Cox model

fm1 = lme(fixed=log(serBilir) ~ 1, random = ~year | id, data=pbc2)
fSurv1 = survreg(Surv(years, status2) ~ drug * age, data=pbc2.id, dist="weibull")
joint_model_fit_1 =  jm(fSurv1, fm1, time_var = "year", n_chains=1L, n_iter=11000L, n_burnin=1000L)


inspecting the coefficients of fSurv1 and the joint model separately, they change sign. The coefficients from the parametric model are AFT coefficients, so they have a different interpretation to the hazard ratios from a proportional hazards model. How do I interpret the coefficients from a joint model with a parametric survival submodel? Is JMbayes2 converting to hazard ratios under the hood? This behaviours also there when I specify a log-logistic parametric model, where it shouldn't be possible to extract hazard ratios from the coefficients, so I am rather confused.

Thank you!

**Comment by jim-rafferty** [comment]
Thanks - just to clarify, there's no difference at all between the two examples given above? Is there any point in fitting the frequentist models at all?

**Comment by drizopoulos** [comment]
The point is to think first how to fit each model separately (which covariates and terms to include), and then as a second step how to combine them in the joint model. From a technical standpoint, we use this approach to extract more easily all the data we need to fit the joint model and get good initial values for the parameters. Also, because JMbayes2 fits interval censored data as well, we need survreg because you cannot specify an interval censoring type when using coxph.


——
Dimitris Rizopoulos
Professor of Biostatistics
Erasmus University Medical Center
The Netherlands
________________________________

**Comment by jim-rafferty** [comment]
Thanks Dimitris. :)
